create table public.school_submissions (
  id bigint generated by default as identity primary key,
  school_name text not null,
  school_code text,
  school_type text not null check (school_type in ('إعدادي', 'تعليم أساسي', 'متعدد المراحل')),
  area text not null check (area in ('حضر', 'ريف')),
  shift text not null check (shift in ('صباحية', 'مسائية', 'ممتدة', 'يوم كامل')),
  available_spaces integer default 0,
  fire_hoses integer not null default 0 check (fire_hoses >= 0),
  water_tanks integer not null default 0 check (water_tanks >= 0),
  water_tanks_status text not null default 'صالح' check (water_tanks_status in ('صالح', 'غير صالح')),
  fire_hydrants integer not null default 0 check (fire_hydrants >= 0),
  principal_name text not null,
  principal_code text,
  principal_national_id text not null check (char_length(principal_national_id) = 14),
  principal_phone text not null,
  principal_type text not null check (principal_type in ('أصلي', 'مكلف')),
  deputy_name text,
  deputy_code text,
  deputy_national_id text,
  deputy_phone text,
  deputy_type text,
  students jsonb not null default '[]'::jsonb,
  status text not null default 'مراجعة' check (status in ('مراجعة', 'مكتمل')),
  created_at timestamptz not null default now()
);

alter table public.school_submissions enable row level security;

create policy "Public can submit school data"
  on public.school_submissions for insert
  with check (true);

create policy "Authenticated managers can read school data"
  on public.school_submissions for select
  to authenticated
  using (true);

-- Temporary demo policies for the local login prototype.
-- Replace these with authenticated-only policies before production deployment.
create policy "Demo can read school data"
  on public.school_submissions for select
  to anon
  using (true);

create policy "Demo can update school data"
  on public.school_submissions for update
  to anon
  using (true)
  with check (true);

create policy "Demo can delete school data"
  on public.school_submissions for delete
  to anon
  using (true);
