-- SQL Migration Script for Supabase SQL Editor
-- This script ensures all columns for form inputs exist in school_submissions

create table if not exists public.school_submissions (
  id bigint generated by default as identity primary key,
  school_name text not null,
  school_code text,
  school_type text not null default 'إعدادي',
  area text not null default 'حضر',
  shift text not null default 'صباحية',
  available_spaces integer default 0,
  fire_hoses integer not null default 0,
  water_tanks integer not null default 0,
  water_tanks_status text not null default 'صالح',
  fire_hydrants integer not null default 0,
  principal_name text not null,
  principal_code text,
  principal_national_id text not null,
  principal_phone text not null,
  principal_type text not null default 'أصلي',
  deputy_name text,
  deputy_code text,
  deputy_national_id text,
  deputy_phone text,
  deputy_type text,
  students jsonb not null default '[]'::jsonb,
  status text not null default 'مراجعة',
  created_at timestamptz not null default now()
);

-- Ensure all columns exist if the table was created previously with fewer fields
alter table public.school_submissions
  add column if not exists school_code text,
  add column if not exists available_spaces integer default 0,
  add column if not exists fire_hoses integer default 0,
  add column if not exists water_tanks integer default 0,
  add column if not exists water_tanks_status text default 'صالح',
  add column if not exists fire_hydrants integer default 0,
  add column if not exists principal_code text,
  add column if not exists deputy_name text,
  add column if not exists deputy_code text,
  add column if not exists deputy_national_id text,
  add column if not exists deputy_phone text,
  add column if not exists deputy_type text,
  add column if not exists students jsonb default '[]'::jsonb,
  add column if not exists status text default 'مراجعة';

-- Enable Row Level Security (RLS) & Policies
alter table public.school_submissions enable row level security;

drop policy if exists "Public can submit school data" on public.school_submissions;
create policy "Public can submit school data"
  on public.school_submissions for insert
  with check (true);

drop policy if exists "Demo can read school data" on public.school_submissions;
create policy "Demo can read school data"
  on public.school_submissions for select
  using (true);

drop policy if exists "Demo can update school data" on public.school_submissions;
create policy "Demo can update school data"
  on public.school_submissions for update
  using (true)
  with check (true);

drop policy if exists "Demo can delete school data" on public.school_submissions;
create policy "Demo can delete school data"
  on public.school_submissions for delete
  using (true);
